dict = {
    "anima, animae, f. ": ["mind", "spirit"],
    "aquila, aquilae, f.": ["eagle", "standard"],
    "avāritia, avāritiae, f.": ["greed"],
    "catēna, catēnae, f.": ["chain"],
    "coma, comae, f.": ["hair", "leaves"],
    "corōna, corōnae, f.": ["crown"],
    "culpa, culpae, f.": ["fault"],
    "fāma, fāmae, f.": ["rumour", "reputation"],
    "fōrma, fōrmae, f.": ["shape", "beauty"],
    "fossa, fossae, f.": ["ditch", "trench"],
    "harēna, harēnae, f.": ["sand"],
    "inopia, inopiae, f.": ["shortage"],
    "iūstitia, iūstitiae, f.": ["justice"],
    "lingua, linguae, f.": ["tongue", "language"],
    "minae, minārum, f. pl.": ["threats"],
    "mora, morae, f.": ["delay"],
    "ōra, ōrae, f.": ["seashore"],
    "praeda, praedae, f.": ["plunder"],
    "rīpa, rīpae, f.": ["river bank"],
    "sagitta, sagittae, f.": ["arrow"],
    "scientia, scientiae, f.": ["knowledge"],
    "tenebrae, tenebrārum, f. pl.": ["darkness"],
    "tuba, tubae, f.": ["trumpet"],
    "avus, avī, m.": ["grandfather"],
    "dolus, dolī, m.": ["trickery"],
    "pontus, pontī, m.": ["sea"],
    "rāmus, rāmī, m.": ["branch"],
    "rēmus, rēmī, m.": ["oar"],
    "somnus, somnī, m.": ["sleep"],
    "umerus, umerī, f.": ["shoulder"],
    "antrum, antrī, n.": ["cave"],
    "argentum, argentī, n.": ["silver"],
    "Capitōlium, Capitōliī, n.": ["the capitoline hill"],
    "exitium, exitiī, n.": ["destruction"],
    "hiberna, hibernōrum, n. pl.": ["winter camp"],
    "hospitium, hospitiī, n.": ["hospitality"],
    "impedimenta, impedimentōrum, n. pl.": ["baggage"],
    "ingenium, ingeniī, n.": ["character", "ability"],
    "iūdicium, iūdiciī, n.": ["trial", "sentence"],
    "lētum, lētī, n.": ["death"],
    "ferrum, ferrī, n.": ["iron", "sword"],
    "ōtium, ōtiī, n.": ["leisure"],
    "pelagus, pelagī, n.": ["open sea"],
    "scūtum, scūtī, n.": ["shield"],
    "similācrum, simulācrī, n.": ["image"],
    "solum, solī, n.": ["ground"],
    "supplicium, suppliciī, n.": ["death penalty"],
    "telum, telī, n.": ["spear", "javelin"],
    "vallum, vallī, n.": ["palisade"],
    "vēlum, vēlī, n.": ["sail"],
    "vēstīgium, vēstīgiī, n.": ["track"],
    "vinculum, vinculī, n.": ["chains"],
    "vulgus, vulgī, n.": ["rabble"],
    "agger, aggeris, m.": ["rampart"],
    "crīnis, crīnis, m.": ["hair"],
    "ēnsis, ēnsis, m.": ["sword"],
    "fūnis, fūnis, m.": ["rope"],
    "genitor, genitōris, m.": ["father"],
    "Mānēs, Mānium, m. pl.": ["spirits of the dead"],
    "mōs, mōris, m.": ["custom", "tradition"],
    "nepōs, nepōtis, m.": ["grandson"],
    "obses, obsidis, m./f.": ["hostage"],
    "pedes, peditis, m.": ["foot soldier", "infantry"],
    "praedō, praedōnis, m.": ["robber"],
    "pudor, pudōris, m.": ["sense of honour"],
    "sermō, sermōnis, m.": ["conversation"],
    "vātēs, vātis, m.": ["prophet"],
    "vesper, vesperis, m.": ["evening"],
    "aestās, aestātis, f.": ["summer"],
    "aetās, aetātis, f.": ["age"],
    "altitūdō, altitūdinis, f.": ["depth", "height"],
    "avis, avis, f.": ["bird"],
    "classis, classis, f.": ["fleet"],
    "coniūrātiō, coniūrātiōnis, f.": ["conspiracy"],
    "contentiō, contentiōnis, f.": ["struggle"],
    "ēruptiō, ēruptiōnis, f.": ["counterattack"],
    "famēs, famis, f.": ["hunger"],
    "fax, facis, f.": ["torch"],
    "imāgō, imāginis, f.": ["form"],
    "iuventūs, iuventūtis, f.": ["youth"],
    "māgnitūdō, māgnitūdinis, f.": ["size"],
    "mōlēs, mōlis, f.": ["mass"],
    "mūnitiō, mūnitiōnis, f.": ["fortification"],
    "nūbēs, nūbis, f.": ["cloud"],
    "occāsiō, occāsiōnis, f.": ["opportunity"],
    "palūs, palūdis, f.": ["swamp"],
    "pellis, pellis, f.": ["skin"],
    "pestis, pestis, f.": ["plague", "destruction"],
    "rūpēs, rūpis, f.": ["cliff"],
    "secūris, secūris, f.": ["axe"],
    "sīdus, sīderis, n.": ["star"],
    "sors, sortis, f.": ["lot", "fortune"],
    "stirps, stirpis, f.": ["lineage"],
    "tellūs, tellūris, f.": ["earth"],
    "turris, turris, f.": ["tower"],
    "voluptās, voluptātis, f.": ["pleasure"],
    "aequor, aequoris, n.": ["sea"],
    "aes, aeris, n.": ["bronze"],
    "aethēr, aetheris, n.": ["sky"],
    "certāmen, certāminis, n.": ["struggle"],
    "cor, cordis, n.": ["heart"],
    "facinus, facinoris, n.": ["crime"],
    "foedus, foederis, n.": ["treaty"],
    "fulmen, fulminis, n.": ["thunder"],
    "fūnus, fūneris, n.": ["funeral"],
    "lūmen, lūminis, n.": ["light"],
    "nemus, nemoris, n.": ["grove"],
    "nūmen, nūminis, n.": ["divinity"],
    "onus, oneris, n.": ["burden"],
    "ōs, ōris, n.": ["face"],
    "os, ossis, n.": ["bone"],
    "pondus, ponderis, n.": ["weight"],
    "adventus, adventūs, m.": ["arrival"],
    "cāsūs, cāsūs, m.": ["chance", "accident", "fall"],
    "cōnsulātus, cōnsulātūs, m.": ["consulship"],
    "cornū, cornūs, n.": ["horn"],
    "equitātus, equitātūs, m.": ["cavalry"],
    "fluctus, fluctūs, n.": ["wave"],
    "impetus, impetūs, m.": ["rush", "attack"],
    "lūctus, lūctus, m.": ["mourning"],
    "sinus, sinūs, m.": ["curve", "bay"],
    "strepitus, strepitūs, m.": ["uproar"],
    "tumultus, tumultūs, m.": ["riot"],
    "versus, versūs, m.": ["verse"],
    "aciēs, aciēī, f.": ["battle-line"],
    "effigiēs, effigiēī, f.": ["likeness"],
    "faciēs, faciēī, f.": ["face"],
    "rēs pūblica, rēī pūblicae, f.": ["state", "government"],
    "acerbus, acerba, acerbum": ["bitter"],
    "adversus, adversa, adversum": ["opposite"],
    "aeturnus, aeturna, aeturnum": ["everlasting"],
    "aliēnus, aliēna, aliēnum": ["foreign"],
    "angustus, angusta, angustum": ["narrow"],
    "arduus, ardua, arduum": ["steep"],
    "asper, aspera, asperum": ["rough"],
    "āter, ātra, ātrum": ["black"],
    "aureus, aurea, aureum": ["golden"],
    "caecus, caeca, caecum": ["blind"],
    "cōnfertus, cōnferta, cōnfertum": ["crowded"],
    "cōnscius, cōnscia, cōnscium": ["aware"],
    "crēber, crēbra, crēbrum": ["frequent", "thick"],
    "cūnctus, cūncta, cūnctum": ["all"],
    "dēfessus, dēfessa, dēfessum": ["exhausted"],
    "dexter, dextra, dextrum": ["right"],
    "dīversus, dīversa, dīversum": ["different from"],
    "dubius, dubia, dubium": ["doubtful"],
    "ēgregius, ēgregia, ēgregium": ["outstanding"],
    "exiguus, exigua, exiguum": ["short"],
    "ferus, fera, ferum": ["wild"],
    "geminus, gemina, geminum": ["twin"],
    "idōneus, idōnea, idōneum": ["suitable"],
    "ignōtus, ignōta, ignōtum": ["unknown"],
    "improbus, improba, improbum": ["wicked"],
    "imprōvisus, imprōvisa, imprōvisum": ["unforeseen"],
    "īmus, īma, īmum": ["lowest"],
    "īnfēstus, īnfēsta, īnfēstum": ["hostile"],
    "integer, integra, integrum": ["whole"],
    "invīsus, invīsa, invīsum": ["hated"],
    "laevus, laeva, laevum": ["left"],
    "lātus, lāta, lātum": ["wide"],
    "liber, libera, liberum": ["free"],
    "obscūrus, obscūra, obscūrum": ["dark"],
    "posterus, postera, posterum": ["following"],
    "reliquus, reliqua, reliquum": ["remaining"],
    "superus, supera, superum": ["upper"],
    "ācer, ācris, ācre": ["sharp"],
    "commūnis, commūne": ["common"],
    "dulcis, dulce": ["sweet"],
    "felīx, felīcis": ["lucky"],
    "mollis, molle": ["soft"],
    "pār, paris": ["equal"],
    "quīcumque, quaecumque, quodcumque": ["whoever", "whatever"],
    "quisque, quaeque, quodque": ["each"],
    "uterque, utraque, utrumque": ["each"],
    "dēferō, dēferre, dētulī, dēlātum": ["carry away"],
    "praesum, praeesse, praefuī (+ dat)": ["be in charge"],
    "licet, licēre, licuit": ["be permitted"],
    "meminī, meminisse": ["remember"],
    "aggredior, aggredī, aggressus sum": ["attack"],
    "praeficiō, praeficere, praefēcī, praefectum": ["put in charge"],
    "experior, experīrī, expertus sum": ["test out"],
    "mūniō, mūnīre, mūnīvī, mūnītum": ["fortify"],
    "accēdō, accēdere, accessī, accessum": ["approach"],
    "addō, addere, addidī, additum": ["add"],
    "caedō, caedere, cecīdī, caesum": ["strike"],
    "colō, colere, coluī, cultum": ["cultivate", "practise", "cherish", "live in"],
    "dēdūcō, dēdūcere, dēdūxī, dēductum": ["withdraw"],
    "dēligō, dēligere, dēlēgī, dēlēctum": ["choose"],
    "īnstituō, īnstituere, īnstituī, īnstitūtum": ["set up"],
    "metuō, metuere, metuī, metūtum": ["fear"],
    "pellō, pellere, pepulī, pulsum": ["drive away"],
    "premō, premere, pressī, pressum": ["press"],
    "prōpōnō, prōpōnere, prōposuī, prōpositum": ["propose"],
    "sē recipere": ["retreat"],
    "solvō, solvere, solvī, solūtum": ["release"],
    "retineō, retinēre, retinuī, retentum": ["hold back"],
    "arbitror, arbitrarī, arbitrātus sum": ["think"],
    "fugō, fugāre, fugāvī, fugātum": ["put to flight"],
    "for, fārī, fātus sum": ["speak"],
    "iūrō, iūrāre, iūrāvī, iūrātum": ["swear"],
    "iuvō, iuvāre, iūvī, iūtum": ["help"],
    "negō, negāre, negāvī, negātum": ["deny", "refuse"],
    "occupō, occupāre, occupāvī, occupātum": ["seize"],
    "praestō, praestāre, praestitī, praestitum": ["stand out"],
    "vastō, vastāre, vastāvī, vastātum": ["devastate"],
    "-ve": ["or"],
    "causā (+ gen)": ["for the sake of"],
    "propter (+ acc)": ["because of"],
    "super (+ abl)": ["on top of"],
    "antequam": ["before"],
    "aut . . . aut": ["either ... or"],
    "vel . . . vel": ["either ... or"],
    "amplius": ["more"],
    "circiter": ["about"],
    "eō": ["in that place", "there", "is"],
    "ferē": ["almost"],
    "interim": ["meanwhile"],
    "itaque": ["and so"],
    "longē": ["far off"],
    "nondum": ["not yet"],
    "parum": ["too little"],
    "prīmum": ["at first"],
    "quā": ["where"],
    "tantum": ["only", "so great"],
    "velut": ["just as"]
}
list = []
stage = []

idx = 848

for key in dict:
    parts = key.split(", ")
    short = parts[0]
    hasPOS = False
    pos = ""
    full = ""
    if (len(parts[-1]) == 2 and parts[-1][1] == '.'):
        pos = parts[-1]
    if (hasPOS):
        full = ", ".join(parts[:-1])
    else :
        full = ", ".join(parts)
    translations = dict[key]

    list.append([short, full, pos, translations])

for i in range(848, 848 + len(dict)):
    stage.append(i)

for entry in list:
    print(str(entry) + ",")

print(str(stage))
